### ISSUE TITLE
Request for Cast School color on channels--

### ISSUE THREAD

**Issue by wwbrandon** [TheTrueIndolent/voodoo-casting-bar#2]
Love your addon and tying to switch from Quartz--

Would you be able to add school coloring for Channeled spelled? Penance vs. Dark Reprimand would be nice to see.

And Power Word: Radiance isn't coloring by school either for some reason.

**Comment by wwbrandon** [comment]
Also isn't seeming to school color every spell. Power Word; Radiance for example.

**Comment by Good-Mojo-Studio** [comment]
Hello and thank you for the comment and your kind words!
Althought the add on takes the school from the combat log, I will investigate it!
I will work more on the school colors on the next updates!

**Comment by wwbrandon** [comment]
Thanks for looking into this, I'm not sure why PW: Radiance wouldn't be included... not colored for Holy. 
![image](https://github.com/user-attachments/assets/a75feff5-299c-4e61-9db9-7b9b36968aaf)
![image](https://github.com/user-attachments/assets/e9208dde-913a-468e-9121-02912935265c)
**_(edit: oh dang I think the school is Radiant, not Holy nvm :D )_**

----------------

But as a Disc Priest I love the roleplay seeing the Holy vs. Shadow casts, would love to see this distinguished between the channel of Penance and Dark Reprimand. Holy vs. Shadow.
![image](https://github.com/user-attachments/assets/fcf8d752-82c3-47a4-8c9c-074afb77faf0)
![image](https://github.com/user-attachments/assets/f91b5856-c6d3-4c7d-9d3a-7a33f4cb9e3d)

---------------

Also noticing when I spam spells sometimes it doesn't fetch the school information- and defaults to standard color?? 
https://github.com/user-attachments/assets/740dd9ce-e8f6-4fce-a476-ecec90e1695b


Already made the switch over, thanks for the addon! Love it!

**Comment by wwbrandon** [comment]
Oh also, think the cast bar is falling is the wrong strata level. It shouldn't be showing on top of the talent panel--

**Comment by Good-Mojo-Studio** [comment]
Hello again and thank you for the infos! I search what was wrong with Discipline Priest and I found that blizzard made a mess with the IDs of the spells! Anyway the version 1.57 should fix the issue with the colors, now I'm looking for the issue with the ticks!

**Comment by wwbrandon** [comment]
Thanks for fixing Penance/Dark Reprimand, they are working great now! Con confirm tho the school is still not fetching properly sometimes when I spam spells-- check this video out to see
https://github.com/user-attachments/assets/740dd9ce-e8f6-4fce-a476-ecec90e1695b

Also, look how this WA incorporates showing GCD, it's beautiful! I could see your addon doing it better with school coloring :D
https://wago.io/-iMgHlW6n

Are there any ways I can support your work? Thanks for taking the reports

----------

![image](https://github.com/user-attachments/assets/b4b90561-7182-4a5e-be90-4353595afd35)
![image](https://github.com/user-attachments/assets/aa604348-7415-4320-b094-6be7348a8d81)

Has a green-ish element to the channel still and a slight different color from the casts?

![image](https://github.com/user-attachments/assets/e63d2bb0-2548-4b47-b28f-c8c8d88b6002)
![image](https://github.com/user-attachments/assets/1c2565d6-9ab1-49e3-9c79-8ea0819a586a)

**Comment by Good-Mojo-Studio** [comment]
Hello there!
I've made some more changes to the colors; I hope they look much prettier now!

**Comment by wwbrandon** [comment]
Thanks man, love it! Did you see how sometimes the color doesn't load when spamming spells?

**Comment by Beverodisc** [comment]
Hi! Disc priest speaking. I have the same issue. When i spam a certain ability (void blast) its just changes in color. And sometimes even to the original green color. So maybe thats something you could possibly look into?

**Comment by Good-Mojo-Studio** [comment]
Hello there and thank you for your constant feedback!
I made more changes to the colors; I hope it will fix the issue!

**Comment by wwbrandon** [comment]
> Hello there and thank you for your constant feedback! I made more changes to the colors; I hope it will fix the issue!

thank you for your attention on this, I'm unable to replicate the bug- so I think it's fixed!

**Comment by wwbrandon** [comment]
Maybe add option to hide Target's Cast's Icon?

**Comment by Good-Mojo-Studio** [comment]
I will add it in the future update! :)

**Comment by wwbrandon** [comment]
Awesome! What about school color vs melee color for target too?

**Comment by wwbrandon** [comment]
Hoping to see the target spell icon hide feature soon?

**Comment by Good-Mojo-Studio** [comment]
Right now, I am trying to make the boss's cast bar more stable! But I will add it soon!

**Comment by wwbrandon** [comment]
awesome thanks man! <3

**Comment by Good-Mojo-Studio** [comment]
Today's update adds the option to hide/show the icon for the target and focus cast bars!

**Comment by wwbrandon** [comment]
Thanks a ton!
